/* ============================================================
   Newton Apple Ads Landing — English content (canonical copy)
   ------------------------------------------------------------
   • This file holds the ENGLISH copy. Vietnamese is in VIcontent.js.
   • One entry per piece of copy. Edit the text between back-ticks ` `.
   • Inline tags (<strong>, <b>, <em>, <span class="accent">) are allowed.
   • Keys MUST match VIcontent.js and the data-i18n attributes in index.html.
   ============================================================ */
window.I18N = window.I18N || {};
window.I18N.en = {
  /* ---- meta ---- */
  _title: `Newton — Apple Ads on autopilot`,
  _desc:  `Newton runs your Apple Search Ads with always-on auto-bidding, full-funnel measurement, and custom product pages — pay only for users who convert.`,

  /* ---- header nav ---- */
  nav_opp: `Why Apple Ads`,
  nav_compare: `Newton vs in-house`,
  nav_platform: `Why Newton`,
  nav_pricing: `Pricing`,
  nav_proof: `Proof`,
  nav_demo: `Request Newton demo`,
  header_cta: `Get the 2026 benchmark`,

  /* ---- hero ---- */
  hero_eyebrow: `APPLE ADS · iOS GROWTH FOR VIETNAM APP STUDIOS`,
  hero_h1: `Apple Ads has no autopilot. Newton is it.`,
  hero_lede: `Newton runs your Apple Search Ads with <span class="accent">always-on auto-bidding</span>, <span class="accent">full-funnel measurement</span>, and <span class="accent">custom product pages</span> at scale — so you lower CAC and pay only for users who actually convert.`,
  hero_cta: `Get the 2026 Apple Ads Benchmark →`,
  hero_trust: `Official Apple Ads Partners globally · 3,000+ App Growth Campaigns · Part of Affle`,

  /* ---- opportunity ---- */
  opp_kicker: `The opportunity`,
  opp_title: `Apple Ads is the highest-intent way to grow on iOS — and the moment is now.`,
  o1_n: `&gt;50%`,
  o1_h: `Tap-to-install conversion`,
  o1_b: `Apple Ads reaches users at the moment they search. That intent converts to installs at over 50% — well above feed-based channels.`,
  o2_n: `0`,
  o2_h: `Ad fraud — self-attributing`,
  o2_b: `Apple-owned inventory means clean, fraud-free installs with built-in attribution — your spend reaches real users.`,
  o3_n: `~2×`,
  o3_h: `High-LTV users`,
  o3_b: `Apple Ads' search-intent users retain up to ~2× better than social — about 30% still active after a month — and higher retention drives higher lifetime value.`,
  o4_n: `64%`,
  o4_h: `of VN installs are iOS`,
  o4_b: `In Vietnam, most installs — and the high-value users — are now on iOS. The App Store is where growth is won.`,
  opp_close: `And Apple is expanding App Store ad inventory in 2026 — more room to grow.`,

  /* ---- why now ---- */
  wn_kicker: `Why now`,
  wn_body: `In 2026, Apple Ads search results become a <span class="accent">multi-slot, relevance-first auction</span>. Bids alone won't win — creative, keywords, and relevance will. That's exactly what Niko, OpticksAI, and Newton's ASO engine are built for.`,
  slots_label: `Every Apple Ads placement Newton can win`,
  s1_t: `Search results`,
  s1_c: `Top + more positions in 2026`,
  s2_t: `Search tab`,
  s2_c: `Before they even type`,
  s3_t: `Today tab`,
  s3_c: `The App Store home page`,
  s4_t: `Product page`,
  s4_c: `On related apps' pages`,

  /* ---- trust band ---- */
  tb1: `<b>Apple Ads Partner</b> — one of only 5 globally`,
  tb2: `<b>3,000+ App Growth Campaigns</b> across gaming, finance &amp; e-commerce`,
  tb3: `Part of <b>Affle</b> — 500+ customers, 20+ cities`,
  tb4: `Trusted by <b>Vietnamese industry leaders</b>`,

  /* ---- Newton vs in-house ---- */
  cmp_kicker: `Newton vs in-house`,
  cmp_title: `The same channel, run a better way.`,
  cmp_head_old: `In-house / Apple dashboard`,
  cmp_head_new: `Newton`,
  cmp_seg_old: `In-house / Apple`,
  cmp_seg_new: `Newton`,
  c1r: `Bidding`,
  c1o: `Manual, hand-set bids; no native autopilot`,
  c1n: `<b>Niko</b> — always-on auto-bidding, optimizing 24/7`,
  c2r: `Measurement`,
  c2o: `Installs only; no down-funnel view`,
  c2n: `<b>Telescope</b> — full-funnel, MMP-integrated (AppsFlyer/Adjust) to revenue`,
  c3r: `Keywords for US/English markets`,
  c3o: `Hand-picked, one language at a time`,
  c3n: `<b>Gen-AI multilingual</b> keyword discovery and recommendations at scale`,
  c4r: `Creative / product pages`,
  c4o: `Built manually, rarely tested`,
  c4n: `<b>OpticksAI</b> — custom product pages at scale, A/B tested`,
  c5r: `What you pay for`,
  c5o: `Media + license + agency fee, win or lose`,
  c5n: `<b>CPCU</b> — pay per converted user, zero platform fee`,
  c6r: `Service &amp; status`,
  c6o: `DIY; not an Apple Ads Partner`,
  c6n: `<b>Apple Ads Partner + done-for-you</b> managed team`,

  /* ---- platform ---- */
  plat_kicker: `Why Newton?`,
  plat_title: `Scale discoverability via platform-led ASO`,
  /* ASO engine — deck slide 14 */
  aso_sub: `Newton's AI-first discoverability engine for ASO — powered by <b>Niko</b> at its core — replaces periodic guesswork with continuous, platform-driven growth, built for the most competitive marketplaces.`,
  a1_t: `Keyword, competition &amp; market intel`,
  a1_b: `Track keywords, market movement, and competitors' custom product pages.`,
  a2_t: `AI store builder`,
  a2_b: `Build optimised listings via AI recommendations for creative and copy.`,
  a3_t: `Prediction &amp; forecasting`,
  a3_b: `Forecast future downloads, rank potential, and conversion rates with predictive modeling.`,
  a4_t: `Impact analysis`,
  a4_b: `Measure the precise impact of any optimization change — before and after an update.`,
  a5_t: `Scalable system`,
  a5_b: `Transforms ASO from a manual task into continuous, platform-driven growth.`,
  /* Telescope — deck slide 16 */
  tele_eyebrow: `Telescope`,
  tele_head: `Your all-in-one growth scorecard.`,
  tele_sub: `An advanced module bringing together Apple Ads, custom product pages, and ASO insights into a single, unified view — so you can act on every lever of growth.`,
  tele_c1: `Smarter decisions`,
  tele_c2: `Opportunities spotted faster`,
  tele_c3: `Stronger performance`,
  demo_cta: `Get Newton platform demo →`,

  /* ---- CPCU ---- */
  cpcu_kicker: `Pricing model`,
  cpcu_title: `Pay for outcomes, not execution.`,
  cpcu_body: `Most teams pay for execution — media spend, a platform license, and an agency fee — whether or not the campaign works. Newton's <span class="accent">CPCU (Cost-Per-Converted-User)</span> flips that: you pay per user who completes the goal that matters — a purchase, a registration, a deposit — with a <span class="accent">zero-platform-fee</span> option. In an expensive US auction, <span class="accent">Newton carries more of the risk</span>, and your cost stays tied to outcomes.`,
  cpcu_cta: `Contact Us`,

  /* ---- proof ---- */
  proof_kicker: `Proof`,
  proof_title: `Apps that grew with Newton.`,
  case1_badge: `Gaming · US / competitive`,
  case1_app: `Taj Rummy`,
  case1_l1: `scale from non-brand`,
  case1_l2: `performance growth`,
  case1_l3: `incrementality`,
  case1_l4: `lower CAC`,
  case2_badge: `Fintech · down-funnel`,
  case2_app: `KreditBee`,
  case2_l1: `installs`,
  case2_l2: `registrations`,
  case2_l3: `loan disbursements`,
  case3_badge: `E-commerce · multilingual`,
  case3_app: `Max Fashion`,
  case3_l1: `installs`,
  case3_l2: `registrations`,
  case3_l3: `purchases`,
  tile1_n: `Fibe`,
  tile1_s: `3X growth, sustaining CAC`,
  tile2_n: `Instamart`,
  tile2_s: `Pilot → #1 performance channel`,
  tile3_n: `PolicyBazaar`,
  tile3_s: `+55.5% month-on-month leads`,
  proof_quote: `By leveraging Newton's AI-powered Apple Ads Campaign Management Platform, Taj Rummy successfully targeted high-value iOS users, achieving exceptional cost efficiency and exponential growth. Newton's advanced capabilities transformed our app performance &amp; long-term profitability to gain a competitive advantage.`,
  proof_who: `— Bhanu Chander, Digital Marketing Manager, Taj Rummy`,
  proof_quote2: `Newton's multi-lingual keyword-based strategies, intelligent competition insights, and precise keyword recommendations, coupled with a comprehensive view of metrics, empowered us to attain our critical conversion objectives for the campaign while keeping it cost efficient.`,
  proof_who2: `— Sneha Chaudhary, Performance Marketing, Max Fashion`,
  proof_quote3: `Newton has helped us to acquire high-quality users by optimizing Apple Ads campaigns, driving higher leads post app downloads. The keyword recommendation tool and smart optimizations has helped us grow our customer base, maintaining overall efficient CPA.`,
  proof_who3: `— Urmesh Chandra, Head of Digital Marketing, Policybazaar`,
  proof_quote4: `Newton's data-driven ASO strategies and A/B testing expertise helped us significantly boost our iOS store CTR from view to download. Their ongoing keyword optimization efforts also drove steady growth in monthly ASO user acquisition. It's been a game changer for our app's visibility and performance.`,
  proof_who4: `— Rabea Elias, Head of Business Development, Almowafir`,
  proof_disc: `Advertiser-reported results. Outcomes vary by app, market, and budget.`,

  /* ---- lead form ---- */
  form_title: `Talk to Newton`,
  form_sub: `Tell us about your app and we'll give you the full picture — how Newton grows your Apple Ads, what it can do for your vertical, and a clear path to get started.`,
  label_name: `Full name <span>*</span>`,
  label_email: `Work email <span>*</span>`,
  err_work_email: `Please use your work email — free/personal addresses (Gmail, Yahoo, etc.) aren't accepted.`,
  label_company: `Company <span>*</span>`,
  label_phone: `Phone`,
  label_role: `Role`,
  label_vertical: `Vertical`,
  label_budget: `Monthly UA budget`,
  label_goal: `Primary goal`,
  label_message: `Message <span>*</span>`,
  opt_select: `Select…`,
  role_1: `Founder / CEO`,
  role_2: `Head of Growth / Marketing`,
  role_3: `UA / Performance / ASO`,
  role_4: `Other`,
  vert_1: `Gaming / Hyper-casual`,
  vert_2: `Fintech / Crypto`,
  vert_3: `E-commerce`,
  vert_4: `Utility / Subscription`,
  vert_5: `Other`,
  budget_1: `Under $5k / mo`,
  budget_2: `$5k – $20k / mo`,
  budget_3: `$20k – $50k / mo`,
  budget_4: `$50k – $150k / mo`,
  budget_5: `$150k+ / mo`,
  budget_6: `Not sure yet`,
  goal_1: `Installs`,
  goal_2: `Trials / eKYC / registrations`,
  goal_3: `Purchases / revenue`,
  goal_4: `Others`,
  form_submit: `Contact us →`,
  form_thanks: `Thanks — we'll reach out within 1 business day to walk you through Newton and how to get started.`,

  /* ---- footer ---- */
  foot_blurb: `Newton by Affle — performance-driven iOS app growth.`,
};
